/*
 * lcd.h
 *
 *  Created on: May 31, 2025
 *      Author: Korisnik
 */

#ifndef CORE_INC_LCD_H_
#define CORE_INC_LCD_H_

#include <stdint.h>

#include "FreeRTOS.h"

//masks
#define LCD_INSTRUCTION_CLEAR_DISPLAY			0x01

#define LCD_INSTRUCTION_RETURN_HOME				0x02

#define LCD_INSTRUCTION_ENTRY_MODE_SET			0x04
#define LCD_ENTRY_MODE_SET_DISPLAY_SHIFT_ON		0x01
#define LCD_ENTRY_MODE_SET_DISPLAY_SHIFT_OFF	0x00
#define LCD_ENTRY_MODE_SET_INCREMENT_ADDR		0x02
#define LCD_ENTRY_MODE_SET_DECREMENT_ADDR		0x00

#define LCD_INSTRUCTION_DISPLAY_CONTROL			0x08
#define LCD_DISPLAY_CONTROL_BLINK_ON			0x01
#define LCD_DISPLAY_CONTROL_BLINK_OFF			0x00
#define LCD_DISPLAY_CONTROL_CURSOR_ON			0x02
#define LCD_DISPLAY_CONTROL_CURSOR_OFF			0x00
#define LCD_DISPLAY_CONTROL_DISPLAY_ON			0x04
#define LCD_DISPLAY_CONTROL_DISPLAY_OFF			0x00

#define LCD_INSTRUCTION_CURSOR_OR_DISPLAY_SHIFT	0x10
#define LCD_CURSOR_OR_DISPLAY_SHIFT_RIGHT		0x04
#define LCD_CURSOR_OR_DISPLAY_SHIFT_LEFT		0x00
#define LCD_CURSOR_OR_DISPLAY_DISPLAY_SHIFT		0x08
#define LCD_CURSOR_OR_DISPLAY_CURSOR_MOVE		0x00

#define LCD_INSTRUCTION_FUNCTION_SET			0x20
#define LCD_FUNCTION_SET_5x10_DOTS				0x04
#define LCD_FUNCTION_SET_5x8_DOTS				0x00
#define LCD_FUNCTION_SET_2_LINES				0x08
#define LCD_FUNCTION_SET_1_LINE					0x00
#define LCD_FUNCTION_SET_8_BITS_INTERFACE		0x10
#define LCD_FUNCTION_SET_4_BITS_INTERFACE		0x00

#define LCD_INSTRUCTION_SET_CGRAM_ADDRESS		0x40

#define LCD_INSTRUCTION_SET_DDRAM_ADDRESS		0x80


typedef enum
{
	LCD_INSTRUCTION = 0,
	LCD_DATA
} LCD_CommandReg;

typedef uint8_t LCD_CommandVal;

typedef struct
{
	LCD_CommandReg reg;
	LCD_CommandVal val;
} LCD_Command;

extern void LCD_Init();

extern void LCD_CommandEnqueue(LCD_CommandReg reg, LCD_CommandVal val);

extern void LCD_CommandEnqueueFromISR(LCD_CommandReg reg, LCD_CommandVal val, BaseType_t *pxHigherPriorityTaskWoken);


#endif /* CORE_INC_LCD_H_ */
